export default [
  { memeImage: "meme.webp" },
  { memeImage: "offline.jpeg" },
  { memeImage: "nomoney.jpeg" },
  { memeImage: "meme4.jpeg" },
  { memeImage: "meme5.jpeg" },
  { memeImage: "meme6.jpeg" },
  { memeImage: "meme7.jpeg" },
  { memeImage: "meme8.jpeg" },
  { memeImage: "meme9.jpeg" },
  { memeImage: "meme10.jpeg" },
  { memeImage: "meme11.jpeg" },
  { memeImage: "meme12.jpeg" },
  { memeImage: "meme13.jpeg" },
  { memeImage: "meme14.jpeg" },
  { memeImage: "meme15.jpeg" },
  { memeImage: "meme16.jpeg" },
  { memeImage: "meme17.jpeg" },
  { memeImage: "meme18.jpeg" },
  { memeImage: "meme19.jpeg" },
  { memeImage: "meme20.jpeg" },
  { memeImage: "meme21.jpeg" },
  { memeImage: "meme22.jpeg" },
  { memeImage: "meme23.jpeg" },
  { memeImage: "meme24.jpeg" },
  { memeImage: "meme25.jpeg" },
  { memeImage: "meme26.jpeg" },
  { memeImage: "meme27.jpeg" },
  { memeImage: "meme28.jpeg" },
  { memeImage: "meme29.jpeg" },
  { memeImage: "meme30.jpeg" },
  { memeImage: "meme31.jpeg" },
  { memeImage: "meme32.jpeg" },
  { memeImage: "meme33.jpeg" },
  //   { memeImage: "meme34.jpeg" },
  //   { memeImage: "meme35.jpeg" },
  //   { memeImage: "meme36.jpeg" },
  //   { memeImage: "meme37.jpeg" },
  //   { memeImage: "meme38.jpeg" },
  //   { memeImage: "meme39.jpeg" },
  //   { memeImage: "meme40.jpeg" },
  //   { memeImage: "meme41.jpeg" },
  //   { memeImage: "meme42.jpeg" },
  //   { memeImage: "meme43.jpeg" },
  //   { memeImage: "meme44.jpeg" },
  //   { memeImage: "meme45.jpeg" },
  //   { memeImage: "meme46.jpeg" },
  //   { memeImage: "meme47.jpeg" },
  //   { memeImage: "meme48.jpeg" },
  //   { memeImage: "meme49.jpeg" },
  //   { memeImage: "meme50.jpeg" },
];
