export default [
  { memeImage: "meme.webp" },
  { memeImage: "offline.jpeg" },
  { memeImage: "nomoney.jpeg" },
  { memeImage: "meme4.jpeg" },
  { memeImage: "meme5.jpeg" },
  { memeImage: "meme6.jpeg" },
  { memeImage: "meme7.jpeg" },
  { memeImage: "meme8.jpeg" },
  { memeImage: "meme9.jpeg" },
  { memeImage: "meme10.jpeg" },
  { memeImage: "meme11.jpeg11" },
  { memeImage: "meme12.jpeg" },
  { memeImage: "meme13.jpeg" },
  { memeImage: "meme14.jpeg" },
  { memeImage: "meme15.jpeg" },
  { memeImage: "meme16.jpeg" },
  { memeImage: "meme17.jpeg" },
  { memeImage: "meme18.jpeg" },
  { memeImage: "meme19.jpeg" },
  { memeImage: "meme20.jpeg" },
  { memeImage: "meme21.jpeg" },
];
